---
- name: "Install Kubernetes masters"
  hosts: k8smasters
  remote_user: root
  roles:
    - k8s-master
     
- name: "Install Kubernetes nodes"
  hosts: k8snodes
  remote_user: root
  roles:
    - k8s-node
