---
- name: "Install Kubernetes masters gluster PODs"
  hosts: k8smasters
  remote_user: "{{ remote_user }}"
  become: "{{ become }}"
  become_user: root
  roles:
    - k8s-gluster-configure

- name: "Configure gluster on nodes"
  hosts: k8snodes
  remote_user: "{{ remote_user }}"
  become: "{{ become }}"
  become_user: root
  roles:
    - k8s-gluster-configure-nodes
