---
kind: Service
apiVersion: v1
metadata:
  name: heketi
  namespace: {{ k8s_gluster_namespace }}
  labels:
    glusterfs: heketi-service
    heketi: service
  annotations:
    description: Exposes Heketi Service
spec:
  selector:
    glusterfs: heketi-pod
  ports:
  - name: heketi
    port:  {{ k8s_heketi_cluster_port }}
    targetPort:  {{ k8s_heketi_cluster_port }} 
