apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: {{ rook_replicapool_name }}
  namespace: {{ rook_namespace }}
spec:
  failureDomain: host
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: {{ rook_storageclass_name }}
provisioner: ceph.rook.io/block
parameters:
  blockPool: {{ rook_replicapool_name }}
  # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
  clusterNamespace: {{ rook_namespace }}
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  fstype: {{ rook_volume_fs }}
# Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/
reclaimPolicy: Retain
