apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: {{ rook_install_name }}
  namespace: {{ rook_namespace }}
spec:
  cephVersion:
    # For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags
    image: ceph/ceph:v14.2.1-20190430
  dataDirHostPath: {{ rook_config_dir }}
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: true
