---
# https://github.com/munnerz/keepalived-cloud-provider/blob/master/README.md
# https://github.com/kubernetes/contrib/blob/master/keepalived-vip/README.md

- name: Configure keepalived cloud provider 
  block:

  - name: Delete deployment.apps/keepalived-cloud-provider em {{ k8s_keepalived_namespace}}
    shell: "kubectl delete -n {{ k8s_keepalived_namespace}} deployment/keepalived-cloud-provider"
    ignore_errors: true
    
  - name: Undeploy keepalived
    block:      
    - name: Delete daemonset.apps/kube-keepalived-vip-ds em {{ k8s_keepalived_namespace}}
      shell: "kubectl delete -n {{ k8s_keepalived_namespace}} daemonset/kube-keepalived-vip-ds"
      ignore_errors: true
    when: k8s_keepalived_vip_deploy==true      
    
  - name: Delete configmap/{{k8s_keepalived_configmap}} em {{ k8s_keepalived_namespace}}
    shell: "kubectl delete -n {{ k8s_keepalived_namespace}} configmap/{{k8s_keepalived_configmap}}"
    ignore_errors: true

  - name: Delete clusterrolebinding/keepalived-vip-clusterrolebinding em {{ k8s_keepalived_namespace}}
    shell: "kubectl delete -n {{ k8s_keepalived_namespace}} clusterrolebinding/keepalived-vip-clusterrolebinding"
    ignore_errors: true

  #- name: Delete clusterrolebinding/keepalived-vip-clusterrolebinding-admin em {{ k8s_keepalived_namespace}}
    #shell: "kubectl delete -n {{ k8s_keepalived_namespace}} clusterrolebinding/keepalived-vip-clusterrolebinding-admin"
    #ignore_errors: true
    
  - name: Delete sa/keepalived-vip-sa em {{k8s_keepalived_namespace}}
    shell: "kubectl delete -n {{ k8s_keepalived_namespace}} sa/keepalived-vip-sa"
    ignore_errors: true

  - name: Delete clusterrole/keepalived-vip-clusterrole
    shell: "kubectl delete clusterrole/keepalived-vip-clusterrole"
    ignore_errors: true
    
  - name: Delete ns/{{k8s_keepalived_namespace}}
    shell: "kubectl delete ns/{{k8s_keepalived_namespace}}"
    ignore_errors: true
    
  when: k8s_external_cluster_controller==true
