---
- name: Remove eth from default routes
  shell: nmcli con mod "System eth0" ipv4.never-default true
  ignore_errors: true

- name: Remove eth from default routes
  shell: ip route del default via 192.168.40.1 dev eth0
  ignore_errors: true  
