---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keepalived-vip-clusterrole
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - endpoints
  - services
  - configmaps
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - endpoints
  - configmaps
  - services/status
  - events
  verbs: ["create", "delete", "update", "patch"] 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keepalived-vip-sa
  namespace: {{k8s_keepalived_namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keepalived-vip-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keepalived-vip-clusterrole
subjects:
- kind: ServiceAccount
  name: keepalived-vip-sa
  namespace: {{k8s_keepalived_namespace}}

