apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: keepalived-cloud-provider
  name: keepalived-cloud-provider
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: keepalived-cloud-provider
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
      labels:
        app: keepalived-cloud-provider
    spec:
      serviceAccount: keepalived-vip-sa
      containers:
      - name: keepalived-cloud-provider
        image: {{k8s_cloud_provider_image}}
        imagePullPolicy: IfNotPresent
        env:
        - name: KEEPALIVED_NAMESPACE
          value: {{k8s_keepalived_namespace}}
        - name: KEEPALIVED_CONFIG_MAP
          value: {{k8s_keepalived_configmap}}
        - name: KEEPALIVED_SERVICE_CIDR
          value: {{ k8s_keepalived_network_range }}
        volumeMounts:
        - name: certs
          mountPath: /etc/ssl/certs
        resources:
          requests:
            cpu: 200m
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 10252
#            host: 127.0.0.1
#          initialDelaySeconds: 15
#          timeoutSeconds: 15
#          failureThreshold: 8
      volumes:
      - name: certs
        hostPath:
          path: /etc/ssl/certs 
