---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: deploy-heketi
  namespace: {{ k8s_gluster_namespace }}
  labels:
    glusterfs: heketi-deployment
    deploy-heketi: deployment
  annotations:
    description: Defines how to deploy Heketi
spec:
  replicas: 1
  template:
    metadata:
      name: deploy-heketi
      labels:
        glusterfs: heketi-pod
        deploy-heketi: pod
    spec:
      serviceAccountName: heketi-service-account
      containers:
      - image: heketi/heketi:latest
        imagePullPolicy: IfNotPresent
        name: deploy-heketi
        env:
        - name: HEKETI_USER_KEY
          value: "{{ k8s_heketi_secret }}"
        - name: HEKETI_ADMIN_KEY
          value: "{{ k8s_heketi_secret }}"
        - name: HEKETI_EXECUTOR
          value: "{{ k8s_heketi_executor }}"
        - name: HEKETI_FSTAB
          value: "/var/lib/heketi/fstab"
        - name: HEKETI_SNAPSHOT_LIMIT
          value: '14'
        - name: HEKETI_KUBE_GLUSTER_DAEMONSET
          value: "y"
        ports:
        - containerPort: {{ k8s_heketi_cluster_port }}
        volumeMounts:
        - name: db
          mountPath: /var/lib/heketi
        - name: config
          mountPath: /etc/heketi
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/hello"
            port: {{ k8s_heketi_cluster_port }}
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: "/hello"
            port: {{ k8s_heketi_cluster_port }}
      volumes:
      - name: db
      - name: config
        secret:
          secretName: heketi-config-secret
