---
- name: Create /etc/sysconfig/docker from docker-sysconfig
  template:
    src: docker-sysconfig
    dest: /etc/sysconfig/docker
    mode: 0644
  when: k8s_use_proxy==true
  
- name: Get /tmp/join-command.sh
  copy:
    src: "/tmp/join-command.sh"
    dest: "/tmp/join-command.sh"
    mode: 0755     
    
- name: Run kubeadm join /tmp/join-command.sh
  shell: "/tmp/join-command.sh"
  args:
    chdir: "/tmp"

#- name: Label this node as node-role.kubernetes.io/node=worker
#  shell: "kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/node=worker"
  
