---
#- name: Run kubeadm join hostname:{{ k8s_master_hostname }} port:{{ k8s_master_port }} token:{{ k8s_token }} hash:{{ k8s_ca_hash }}
#  shell: "kubeadm join --token {{ k8s_token }} {{ k8s_master_hostname }}:{{ k8s_master_port }} --discovery-token-ca-cert-hash sha256:{{ k8s_ca_hash }}"
#  args:
#    chdir: "/tmp"

- name: Create /etc/sysconfig/docker from docker-sysconfig
  template:
    src: docker-sysconfig
    dest: /etc/sysconfig/docker
    mode: 0644
  when: k8s_use_proxy==true
  
- name: Get /tmp/join-command.sh
  copy:
    src: "/tmp/join-command.sh"
    dest: "/tmp/join-command.sh"
    mode: 0755     
    
- name: Run kubeadm join /tmp/join-command.sh
  shell: "/tmp/join-command.sh"
  args:
    chdir: "/tmp"

# To set the label for the node
#- name: Label this node as node-role.kubernetes.io/node=worker
#  shell: "kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/node=worker"
  
