---
- name: Criar {{k8s_guest_base_directory}}/k8s-master
  file:
    path: '{{k8s_guest_base_directory}}/k8s-master'
    state: directory

- name: Create k8s-master1
  shell: > 
    virt-install \
    -n k8s-master1 \
    --description='Kubernetes master 1 machine' \
    --os-type=Linux \
    --os-variant=generic \
    --ram={{k8s_guest_master_ram}} \
    --vcpus={{k8s_guest_master_cpu}} \
    --graphics=vnc \
    --noautoconsole \
    --disk path={{k8s_guest_base_directory}}/k8s-master1/k8s-master1.img,bus=virtio,size={{k8s_guest_master_root_disk}} \
    --pxe \
    --boot=hd,network \
    --check-cpu \
    --network=bridge:{{k8s_guest_bridge_device}},model=virtio,mac={{k8s_guest_master_mac_addr}}"

- name: Criar {{k8s_guest_base_directory}}/k8s-node1
  file:
    path: '{{k8s_guest_base_directory}}/k8s-node1'
    state: directory

- name: Create k8s-node1
  shell: > 
    virt-install \
    -n k8s-node1 \
    --description='Kubernetes node1 1 machine' \
    --os-type=Linux \
    --os-variant=generic \
    --ram={{k8s_guest_worker_ram}} \
    --vcpus={{k8s_guest_worker_cpu}} \
    --graphics=vnc \
    --noautoconsole \
    --disk path={{k8s_guest_base_directory}}/k8s-node1/k8s-node1.img,bus=virtio,size={{k8s_guest_worker_root_disk}} \
    --disk path={{k8s_guest_base_directory}}/k8s-node1/k8s-node1-data.img,bus=virtio,size={{k8s_guest_worker_data_disk}} \    
    --pxe \
    --boot=hd,network \
    --check-cpu \
    --network=bridge:{{k8s_guest_bridge_device}},model=virtio,mac={{k8s_guest_worker1_mac_addr}}"
 
- name: Criar {{k8s_guest_base_directory}}/k8s-node2
  file:
    path: '{{k8s_guest_base_directory}}/k8s-node2'
    state: directory

- name: Create k8s-node2
  shell: > 
    virt-install \
    -n k8s-node2 \
    --description='Kubernetes node2 1 machine' \
    --os-type=Linux \
    --os-variant=generic \
    --ram={{k8s_guest_worker_ram}} \
    --vcpus={{k8s_guest_worker_cpu}} \
    --graphics=vnc \
    --noautoconsole \
    --disk path={{k8s_guest_base_directory}}/k8s-node2/k8s-node2.img,bus=virtio,size={{k8s_guest_worker_root_disk}} \
    --disk path={{k8s_guest_base_directory}}/k8s-node2/k8s-node2-data.img,bus=virtio,size={{k8s_guest_worker_data_disk}} \    
    --pxe \
    --boot=hd,network \
    --check-cpu \
    --network=bridge:{{k8s_guest_bridge_device}},model=virtio,mac={{k8s_guest_worker1_mac_addr}}" 

- name: Criar {{k8s_guest_base_directory}}/k8s-node3
  file:
    path: '{{k8s_guest_base_directory}}/k8s-node3'
    state: directory

- name: Create k8s-node3
  shell: > 
    virt-install \
    -n k8s-node3 \
    --description='Kubernetes node3 1 machine' \
    --os-type=Linux \
    --os-variant=generic \
    --ram={{k8s_guest_worker_ram}} \
    --vcpus={{k8s_guest_worker_cpu}} \
    --graphics=vnc \
    --noautoconsole \
    --disk path={{k8s_guest_base_directory}}/k8s-node3/k8s-node3.img,bus=virtio,size={{k8s_guest_worker_root_disk}} \
    --disk path={{k8s_guest_base_directory}}/k8s-node3/k8s-node3-data.img,bus=virtio,size={{k8s_guest_worker_data_disk}} \    
    --pxe \
    --boot=hd,network \
    --check-cpu \
    --network=bridge:{{k8s_guest_bridge_device}},model=virtio,mac={{k8s_guest_worker1_mac_addr}}"     
    
- name: Wait 300 seconds for {{k8s_node3}} port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{k8s_node3}}'
    search_regex: OpenSSH
    delay: 10
    
- name: Import k8s-master SSH key
  shell: "ssh-keyscan -t rsa {{k8s_master}} >> ~/.ssh/known_hosts"

- name: Import k8s-node1 SSH key
  shell: "ssh-keyscan -t rsa {{k8s_node1}} >> ~/.ssh/known_hosts"

- name: Import k8s-node2 SSH key
  shell: "ssh-keyscan -t rsa {{k8s_node2}} >> ~/.ssh/known_hosts"

- name: Import k8s-node3 SSH key
  shell: "ssh-keyscan -t rsa {{k8s_node3}} >> ~/.ssh/known_hosts"
