---
- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no  

- name: Disable SE Linux
  selinux:
    state: disabled 
  
- name: Install bind-utils
  package:
    name: bind-utils
    state: latest

- name: Install yum-utils
  package:
    name: yum-utils
    state: latest
    
- name: Install nfs-utils
  package:
    name: nfs-utils
    state: latest

- name: Install unzip
  package:
    name: unzip
    state: latest

- name: Install openssl
  package:
    name: openssl
    state: latest

- name: Install git
  package:
    name: git
    state: latest

- name: Install glusterfs-client
  package:
    name: glusterfs-client
    state: latest

- name: Install docker
  package:
    name: docker 
    state: latest
    
- name: Create /etc/systemd/system/docker.service.d/http-proxy.conf
  template:
    src: docker-http-proxy.conf
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    mode: 0644
  when: k8s_use_proxy==true
    
- name: Start docker
  service:
    name: docker
    enabled: yes  
    state: started
    
- name: Create /etc/yum.repos.d/kubernetes.repo
  copy:
    src: k8s-repo
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: 0644

- name: Create /etc/modules-load.d/overlay.conf
  copy:
    src: overlay.conf
    dest: /etc/modules-load.d/overlay.conf
    mode: 0644
    
- name: Create /etc/modules-load.d/ip_vs.conf
  copy:
    src: ip_vs.conf
    dest: /etc/modules-load.d/ip_vs.conf
    mode: 0644
    
- name: ModProbe ip_vs
  modprobe:
    name: ip_vs
    state: present    

- name: ModProbe overlay
  modprobe:
    name: overlay
    state: present 
    
- name: Install kubelet
  package:
    name: kubelet 
    state: latest
    disable_gpg_check: yes

- name: Install kubeadm
  package:
    name: kubeadm 
    state: latest
    disable_gpg_check: yes

- name: Install kubectl
  package:
    name: kubectl 
    state: latest
    disable_gpg_check: yes

- name: Start kubelet
  service:
    name: kubelet
    enabled: yes  
    state: started
    
- name: Setting net.bridge.bridge-nf-call-iptables to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: Setting net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

